# Generated by Django 4.1.5 on 2023-05-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="complaint_id",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
