# Generated by Django 4.1.7 on 2023-05-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeinfo',
            old_name='isFix',
            new_name='isBroken',
        ),
    ]
