# Generated by Django 4.1.5 on 2023-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0002_remove_reservation_reservation_bike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Reservation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
