# Generated by Django 4.1.5 on 2023-05-14 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bike_app", "0002_alter_complaint_complaint_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikeinfo",
            name="BikePicture",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
