# Generated by Django 4.1.5 on 2023-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike_app", "0003_bikeinfo_bikepicture"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikeinfo",
            name="BikeSize",
            field=models.CharField(default="General", max_length=300),
        ),
        migrations.AddField(
            model_name="reservation",
            name="Reservation_Number",
            field=models.CharField(default="000", max_length=5),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Reservation_Bike",
            field=models.CharField(
                choices=[("bike1", "Bike 1"), ("bike2", "Bike 2"), ("bike3", "Bike 3")],
                max_length=20,
            ),
        ),
    ]
