# Generated by Django 4.1.5 on 2023-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike_app", "0004_bikeinfo_bikesize_reservation_reservation_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikeinfo",
            name="BikePrice",
            field=models.CharField(default="999", max_length=20),
        ),
    ]
