# Generated by Django 4.1.7 on 2023-06-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeinfo',
            name='image',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
