# Generated by Django 4.1.5 on 2023-05-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike_app", "0005_bikeinfo_bikeprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account",
            field=models.FloatField(default=0, max_length=50),
        ),
    ]
