# Generated by Django 4.1.7 on 2023-06-11 11:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0005_bikeinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikeinfo',
            name='image',
            field=models.ImageField(default='', upload_to='static/BikesImage'),
        ),
    ]
