# Generated by Django 4.1.5 on 2023-06-12 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bike_app", "0006_customuser_account"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="Reservation_Bike",),
        migrations.RemoveField(model_name="reservation", name="Reservation_DateEnd",),
        migrations.RemoveField(
            model_name="reservation", name="Reservation_DateRequest",
        ),
        migrations.RemoveField(model_name="reservation", name="Reservation_Number",),
        migrations.RemoveField(model_name="reservation", name="Reservation_status",),
        migrations.AddField(
            model_name="reservation",
            name="delivery_method",
            field=models.CharField(
                choices=[("pick_up", "Pick Up"), ("delivery", "Delivery")],
                default="pick_up",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="finish_day",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reservation",
            name="insurance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="pickup_point",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Warszawa Zachodnia", "Warszawa Zachodnia"),
                    ("Warszawa Centralna", "Warszawa Centralna"),
                    ("Warszawa Wschodnia", "Warszawa Wschodnia"),
                ],
                default="Warszawa Centralna",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_day",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Reservation_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
